name: Update README.md

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  update-readme:
    
    name: Update this repo's README
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      
      - name: Generate my JSON
        run: |
            pip3 install requests numpy
            python3 scripts/Main.py ${{ secrets.username }} ${{ secrets.password }} 
      
      - name: Commit changes      
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "GitHub Actions"
          author_email: "githubactions@github.com.br"
          committer_name: "GitHub Actions"
          committer_email: "githubactions@github.com.br"
          message: "Updated README.md Data"
          github_token: ${{ secrets.GH_TOKEN }}

      - name: Generate Waka Stats
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TIME: true
          SHOW_MASKED_TIME: true
          COMMITTER_NAME: "GitHub Actions"
          COMMITTER_EMAIL: "githubactions@github.com.br"
          AUTHOR_NAME: "GitHub Actions"
          AUTHOR_EMAIL: "githubactions@github.com.br"          

      - name: Generate Waka Stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: "False"
          SHOW_LOC_CHART: "False"
          SHOW_PROFILE_VIEWS: "False" 
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_TIMEZONE: "False"
          SHOW_UPDATED_DATE: "False"
          SHOW_LINES_OF_CODE: "True"
          SHOW_LANGUAGE: "False"
          SHOW_OS: "False"
          SHOW_EDITORS: "False"
          LOCALE: "en"          
